// Copyright (c) 2012 The LevelDB Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file. See the AUTHORS file for names of contributors.

#include "leveldb/filter_policy.h"

#include "leveldb/slice.h"
#include "util/hash.h"

namespace leveldb {

namespace {
static uint32_t BloomHash(const Slice& key) {
  return Hash(key.data(), key.size(), 0xbc9f1d34);
}

// n个元素的set、m位的bit数组、k个hash函数
// Q: 当n和m已知，那k取多少合适？
// A: k = ln2*(m/n) 最合适

class BloomFilterPolicy : public FilterPolicy {
 public:
  // bits_per_key就是m/n
  // 构造的时候由调用者指定
  explicit BloomFilterPolicy(int bits_per_key) : bits_per_key_(bits_per_key) {
    // We intentionally round down to reduce probing cost a little bit
    // k = ln2*(m/n)
    k_ = static_cast<size_t>(bits_per_key * 0.69);  // 0.69 =~ ln(2)
    // k属于[1,30]
    if (k_ < 1) k_ = 1;
    if (k_ > 30) k_ = 30;
  }

  const char* Name() const override { return "leveldb.BuiltinBloomFilter2"; }

  // 这里使用一系列key来创建bloom filter
  void CreateFilter(const Slice* keys, int n, std::string* dst) const override {
    // Compute bloom filter size (in both bits and bytes)
    // m位
    size_t bits = n * bits_per_key_;

    // For small n, we can see a very high false positive rate.  Fix it
    // by enforcing a minimum bloom filter length.
    // 为了降低假阳性率，m不能太小
    // 最小只能为64位
    if (bits < 64) bits = 64;
    // 向上取整为8的倍数
    size_t bytes = (bits + 7) / 8;
    bits = bytes * 8;
    // 扩大输出空间给位数组
    // 相当于push_back了bytes个0
    const size_t init_size = dst->size();
    dst->resize(init_size + bytes, 0);
    // 压入k_
    dst->push_back(static_cast<char>(k_));  // Remember # of probes in filter
    // 取得要写入的首址
    char* array = &(*dst)[init_size];
    // 依次处理每一个key
    for (int i = 0; i < n; i++) {
      // Use double-hashing to generate a sequence of hash values.
      // See analysis in [Kirsch,Mitzenmacher 2006].
      // 算hash
      uint32_t h = BloomHash(keys[i]);
      // LevelDB并没有严格的设计k_个hash函数
      // 而是将第一次的hash值通过简单的移位来得到其余k_-1个hash值
      const uint32_t delta = (h >> 17) | (h << 15);  // Rotate right 17 bits
      for (size_t j = 0; j < k_; j++) {
        const uint32_t bitpos = h % bits;
        array[bitpos / 8] |= (1 << (bitpos % 8));
        h += delta;
      }
    }
  }

  // 检查是否存在
  // 其中bloom_filter就是m位bit数组+k_
  // 也就是CreateFilter()中写入的内容
  bool KeyMayMatch(const Slice& key, const Slice& bloom_filter) const override {
    const size_t len = bloom_filter.size();
    if (len < 2) return false;

    const char* array = bloom_filter.data();
    const size_t bits = (len - 1) * 8;

    // Use the encoded k so that we can read filters generated by
    // bloom filters created using different parameters.
    const size_t k = array[len - 1];
    // 如果hash函数值大于30，那么直接返回存在
    // 为什么？不知道
    if (k > 30) {
      // Reserved for potentially new encodings for short bloom filters.
      // Consider it a match.
      return true;
    }

    uint32_t h = BloomHash(key);
    const uint32_t delta = (h >> 17) | (h << 15);  // Rotate right 17 bits
    for (size_t j = 0; j < k; j++) {
      const uint32_t bitpos = h % bits;
      // 有一位不匹配就是false
      if ((array[bitpos / 8] & (1 << (bitpos % 8))) == 0) return false;
      h += delta;
    }
    return true;
  }

 private:
  size_t bits_per_key_;
  size_t k_;
};
}  // namespace

const FilterPolicy* NewBloomFilterPolicy(int bits_per_key) {
  return new BloomFilterPolicy(bits_per_key);
}

}  // namespace leveldb
